// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormQuery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"api-go/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newFailedJob(db *gorm.DB) failedJob {
	_failedJob := failedJob{}

	_failedJob.failedJobDo.UseDB(db)
	_failedJob.failedJobDo.UseModel(&model.FailedJob{})

	tableName := _failedJob.failedJobDo.TableName()
	_failedJob.ALL = field.NewField(tableName, "*")
	_failedJob.ID = field.NewString(tableName, "id")
	_failedJob.Connection = field.NewString(tableName, "connection")
	_failedJob.Queue = field.NewString(tableName, "queue")
	_failedJob.Payload = field.NewString(tableName, "payload")
	_failedJob.Exception = field.NewString(tableName, "exception")
	_failedJob.FailedAt = field.NewTime(tableName, "failed_at")

	_failedJob.fillFieldMap()

	return _failedJob
}

type failedJob struct {
	failedJobDo failedJobDo

	ALL        field.Field
	ID         field.String
	Connection field.String
	Queue      field.String
	Payload    field.String
	Exception  field.String
	FailedAt   field.Time

	fieldMap map[string]field.Expr
}

func (f failedJob) Table(newTableName string) *failedJob {
	f.failedJobDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f failedJob) As(alias string) *failedJob {
	f.failedJobDo.DO = *(f.failedJobDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *failedJob) updateTableName(table string) *failedJob {
	f.ALL = field.NewField(table, "*")
	f.ID = field.NewString(table, "id")
	f.Connection = field.NewString(table, "connection")
	f.Queue = field.NewString(table, "queue")
	f.Payload = field.NewString(table, "payload")
	f.Exception = field.NewString(table, "exception")
	f.FailedAt = field.NewTime(table, "failed_at")

	f.fillFieldMap()

	return f
}

func (f *failedJob) WithContext(ctx context.Context) *failedJobDo {
	return f.failedJobDo.WithContext(ctx)
}

func (f failedJob) TableName() string { return f.failedJobDo.TableName() }

func (f *failedJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *failedJob) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["id"] = f.ID
	f.fieldMap["connection"] = f.Connection
	f.fieldMap["queue"] = f.Queue
	f.fieldMap["payload"] = f.Payload
	f.fieldMap["exception"] = f.Exception
	f.fieldMap["failed_at"] = f.FailedAt
}

func (f failedJob) clone(db *gorm.DB) failedJob {
	f.failedJobDo.ReplaceDB(db)
	return f
}

type failedJobDo struct{ gen.DO }

func (f failedJobDo) Debug() *failedJobDo {
	return f.withDO(f.DO.Debug())
}

func (f failedJobDo) WithContext(ctx context.Context) *failedJobDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f failedJobDo) Clauses(conds ...clause.Expression) *failedJobDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f failedJobDo) Not(conds ...gen.Condition) *failedJobDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f failedJobDo) Or(conds ...gen.Condition) *failedJobDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f failedJobDo) Select(conds ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f failedJobDo) Where(conds ...gen.Condition) *failedJobDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f failedJobDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *failedJobDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f failedJobDo) Order(conds ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f failedJobDo) Distinct(cols ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f failedJobDo) Omit(cols ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f failedJobDo) Join(table schema.Tabler, on ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f failedJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f failedJobDo) RightJoin(table schema.Tabler, on ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f failedJobDo) Group(cols ...field.Expr) *failedJobDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f failedJobDo) Having(conds ...gen.Condition) *failedJobDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f failedJobDo) Limit(limit int) *failedJobDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f failedJobDo) Offset(offset int) *failedJobDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f failedJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *failedJobDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f failedJobDo) Unscoped() *failedJobDo {
	return f.withDO(f.DO.Unscoped())
}

func (f failedJobDo) Create(values ...*model.FailedJob) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f failedJobDo) CreateInBatches(values []*model.FailedJob, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f failedJobDo) Save(values ...*model.FailedJob) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f failedJobDo) First() (*model.FailedJob, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FailedJob), nil
	}
}

func (f failedJobDo) Take() (*model.FailedJob, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FailedJob), nil
	}
}

func (f failedJobDo) Last() (*model.FailedJob, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FailedJob), nil
	}
}

func (f failedJobDo) Find() ([]*model.FailedJob, error) {
	result, err := f.DO.Find()
	return result.([]*model.FailedJob), err
}

func (f failedJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FailedJob, err error) {
	buf := make([]*model.FailedJob, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f failedJobDo) FindInBatches(result *[]*model.FailedJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f failedJobDo) Attrs(attrs ...field.AssignExpr) *failedJobDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f failedJobDo) Assign(attrs ...field.AssignExpr) *failedJobDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f failedJobDo) Joins(field field.RelationField) *failedJobDo {
	return f.withDO(f.DO.Joins(field))
}

func (f failedJobDo) Preload(field field.RelationField) *failedJobDo {
	return f.withDO(f.DO.Preload(field))
}

func (f failedJobDo) FirstOrInit() (*model.FailedJob, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FailedJob), nil
	}
}

func (f failedJobDo) FirstOrCreate() (*model.FailedJob, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FailedJob), nil
	}
}

func (f failedJobDo) FindByPage(offset int, limit int) (result []*model.FailedJob, count int64, err error) {
	if limit <= 0 {
		return
	}

	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Count()
	return
}

func (f failedJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f *failedJobDo) withDO(do gen.Dao) *failedJobDo {
	f.DO = *do.(*gen.DO)
	return f
}
