apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    NOCAPTCHA_SECRET: ENC[AES256_GCM,data:3eXSkuWRM0XgQSx/o51cYL4Yast9ghNwHqop1Ms5eKldRMUicbyhdw==,iv:7lfcF837EOB8vXVUaY2OUzzOTmJORMmm7BlVzYUXDlo=,tag:2DTV5iDefBetJvjY3f2fzw==,type:str]
    NOCAPTCHA_SITEKEY: ENC[AES256_GCM,data:Gg4OsoEQnZNJotGrdw4rQszLeWhdwRnxjhzodTrRfhcZ+/tBLfqilg==,iv:JQ1f6x53WKUWEa6I+rvO+OnaeMQoiV9gC0YcQeolKlw=,tag:upX/i+wiSxsUWqKcjMCp2A==,type:str]
    SENTRY_LARAVEL_DSN: ENC[AES256_GCM,data:FV3ei58F+BoYUjX4MfkEwuQpH1SNoyvmEWPAhO8FlBfiOLaCEHaiX72VraZYmgLI5JGtPcl7kXYRHKVFeVViYTxO1c/uNivviQ==,iv:AP0oWYiruUpoW2jj4+MlWbjMII48L5vFilO7BFaEYOM=,tag:BZmqtubY/jdkeUkIOU+M+w==,type:str]
    APP_KEY: ENC[AES256_GCM,data:KXoV7BXLU/1519fSFZUuULBwx8R6AesAnQq7jg2SHyjdyoSplv+gl9MwsBuZoKqTntpU,iv:azdat5qWPuz9mj/30nESDhickLgsqE53PjlvnJbuxQM=,tag:IPi0GR+CETwfot735q4CSg==,type:str]
    KEYCLOAK_MASTER_USERNAME: ENC[AES256_GCM,data:54w2hTo=,iv:qCqMy9A2hcXRLU+hOHEiPff9cskLXo+mz6fwQocxNg8=,tag:yAESSf+wySxtcuzrtabqAw==,type:str]
    KEYCLOAK_MASTER_PASSWORD: ENC[AES256_GCM,data:LeI9FGUXV0ZQqcEOcAke95jeoWM=,iv:sWkmzB+jqFNHRKze4s0yWDUE5XAQ/FynPqoNyQeuLbo=,tag:4lDe9/ybNGomw/s/F6IqUw==,type:str]
    ALGOLIA_APP_ID: ENC[AES256_GCM,data:wAYBzfHVmqm+XA==,iv:cJTL4Y6x+cB0NdRtEnNGSfdj5Yy5a9cZ+DsowjaXux0=,tag:HEr4P10ZBYIicBy6e6k2uw==,type:str]
    ALGOLIA_SECRET: ENC[AES256_GCM,data:1lz64MGPe33CURKNR3JKdlTYX5lbyCo8voN+FFndHQg=,iv:6QnsgUeFAbP735V5leBOMKLey3peE901tISdM5y3P2k=,tag:heJl8XEQQYBSHfk70YAnng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:rom2LaY=,iv:dDgOyOtzzKLr0Lo2yT/RYxPp3LIracNbDJDJLzaKI9E=,tag:kfmDDNo3MbjGFgo9OOKjDA==,type:str]
    password: ENC[AES256_GCM,data:eT5miDE=,iv:RvoYNqO/LEX6/Cp38dOqDm06hh/9+ihvF2wQISe3TO0=,tag:dnoupNaCQdwvMNqqYd55nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:CVaDz0s=,iv:T5qOWdtAUXESKp6JFilrh/oFqYxR91Y8iyg5FYvtdUY=,tag:lW2ghjly5O4BYDh7EUED9A==,type:str]
    password: ENC[AES256_GCM,data:Y181jIPOhCXDiNZTlq+Db4sOOVo=,iv:2ov72CcAKtP3vHzKXbo4d9s8V1Wl7Jr4X5R3q5woA8Q=,tag:pGlXnulkPunjlUJ3VG4xiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-assets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:JcJOV9STXQhbW4F+r0XFe5p05js=,iv:bZTllvE0uSKpR7Mh0u+V4a9gRkASk3xyz31/zrXXj3g=,tag:aF2k5GzqsAEnMvtGcN4aLA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:7RQd4NjdKQlZ+/gT8q+AmL95zMFuWFCtlm/YDNxUyJ06USPc,iv:sHX409B40odg1r7IKIfiZI5REdg3HSphErd5wdY3xW8=,tag:07y2kvcBOwLnF4nG61Jw5A==,type:str]
    region: ENC[AES256_GCM,data:O2TUoVMq,iv:kcPA05KYULmwL8DxIvqZwhOntXf4mr7ryBB1jJZaZY4=,tag:4SXWIiuufLDSpAhn5znXvQ==,type:str]
    bucket: ENC[AES256_GCM,data:Y+2txUt5vgggUw8hwQ==,iv:z/2ZfLcumSDjvKCrRNQMvDDz187/UFzqpbdmGywFk60=,tag:VQ8IQNSdV5jpPW+ieB4VxA==,type:str]
    endpoint: ENC[AES256_GCM,data:p0xGk/t1GahkxLVwbcPgdx8XDMISVUE05dR8,iv:EuMKwC/3sUkeYZkjxJThkLvRXokLVQn9I0va84yHuMg=,tag:EhYrQQPIrDAECujGdtBDVw==,type:str]
    cdn: ENC[AES256_GCM,data:X71o3TO6MAxk6oLcRbkf5ebt8Sy+uIm0xJJe5Ho20lCZPuQTT70Bxvw=,iv:X2/bEfSnPSlwWtlNddnNqXA6AgIbUSiwI0+Yl8EJCdw=,tag:7MkWPRQFVN0cW/oaJx5ezA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:Bm4sBEIRigQn2EmpG3h3QA3EjZ0=,iv:f+U28jQP1nqfVpA8TR//JfRCaHmJvQHfpCW7tVn+X2Y=,tag:4wEzXLAzQV4EbQ8m1KoXSw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:SPEy5Bj1VAItIZnLNW2deV1jhi0jG4zm/zXKtV/UlEIbTEbH,iv:nW5dFyBqO2QiD/T3J6NbvonAJ06UpkXlCzwWwGHCUxg=,tag:PBA/WSyGljB721unJvUD6g==,type:str]
    region: ENC[AES256_GCM,data:fc601QoW,iv:pWloxVA3d6BRB/pde+eMrv13ZBung9KPTarXpy7txlg=,tag:JOqjexPtFLIKKUQcZGgNiA==,type:str]
    bucket: ENC[AES256_GCM,data:iJFZrDgfmHeMiRJABJpmogk=,iv:GeYY4qVW7e82cZ0VIC1zT5ML8GYVckyB4uHVR0pqvi8=,tag:eH0rVCuWGzPQ/6aDmgSmWw==,type:str]
    endpoint: ENC[AES256_GCM,data:mEaTfCggZEebFmQgKdeWuldZmzh7V7ZxPc5V,iv:nwawfv+135M1ItVtPIj6jOQJ2d/hFpcljKnxPs8yf0c=,tag:vkHBpDQ+A8eY1rX5BYIuEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ses
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:YHfSFHm6tLqKA+lYx1jbfTJizqU=,iv:gnJOoLm5Zm7ELDtb1FmcRtlkVPX+uWVv6MQq6XQt1js=,tag:XCi5z2Y6VQuuQDjt4f5hbA==,type:str]
    secret: ENC[AES256_GCM,data:OXPbhyzfrlZ7PBCfn+UazhKNIXKYUjjU46jsGrnlkKmXLdmHqKLxFA==,iv:fonLooK3gvcQe4LP/uvukzO1OuQ94EAGNqPDElMuJLs=,tag:pZ2bF3Ax6L9dIGVXB0PndA==,type:str]
    region: ENC[AES256_GCM,data:Oqghi1M44nFI,iv:8UyT9cl6YbuaXBT3ytgX+2YbjBWtQWOK1PfQADTm7u4=,tag:54aT1K/pCUoVh7+hTkZ4tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: google-analytics
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    trackingId: ENC[AES256_GCM,data:q/D8wViekSO07XXHg+U=,iv:Ievk4U6nQAzt1epa4pzzb/IsWHwpmo4Fk3UwV2ltYYY=,tag:FBuNGp6HI7cJbosVmCjPLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-exporter
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    DATA_SOURCE_NAME: ENC[AES256_GCM,data:g6VI1ojKUTr2Votgt39w75Fq8BtB3ly/NSFA0UCDhgQfgl3MUcsaM133yCgtCDmoIliDyz7YWjs=,iv:iAzIlW1QGDbJbfkJ71GIS+R6Run3XIXISsJzaMbrkVM=,tag:gCO+fNXWLJ1+8PU17UJH3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T23:33:38Z'
    mac: ENC[AES256_GCM,data:QUlalgaX2cp/R3OhSNNdiloP0kYZTKkMWu45XUuWOjk4/wzm3Cz0MIoFt6rcixARtReeDZTegCSDe3aILlEZ7AkG3ALEoAsLao7Pgp0y6kz6tCJ6s6NymQ5lAtQnhoi16a5ecPoibOiFQOGgnF4OYboACXPXP9Z9KroF674PzHI=,iv:H6n5xB5NFki1LoqdnP496Y78QZi7Ow4Y+EILrwkV0qo=,tag:U7JV6B7TpEbTndWZvIGoJg==,type:str]
    pgp:
    -   created_at: '2021-03-16T23:33:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAonDAgFgFAQ2Ffr2o3jUXLRd6tq5l97o6eEAbJpurK2JS
            Q/hQVsR2l2dOBZ6ObwifJ9/7NgK0JVw59FnwGpqdodY5d+a5rfnksiqpZN/HhdU4
            aEHaSPH7JBrjrX4xhv+TFo4JqtVvGDeOO8puoyd5cQqPTnP++gzrEPPqc8lz4nuP
            GuPX9npB66yqMJVwF7qGFDOAsgNMeQvQdJgqZBBLRWNdjVXIYb+SWZwkgg2Oc1wu
            GBToHQPwB81dFhrC56n3pvOd/H7wpDAAqi3/IH2VCxbWUPNiuqGIAwgYYQ1PBeIj
            BHdlE1mdlPN0asgvlfgu9NDDpl5NIArx1NBnLf3a+wGlJ3TeQKkiyROKKC/yfTSq
            iVT66cBMW+/l1/j5wgW+g9wl2cdKPyfWRKCoJKjJgCFfS0pmPVF2YeeuUrr1afnC
            NOHnNlIKFp877qoT6TbeBF0oVG4VUxn2On4apihhwM/JfyBHdJvS1FUbIoPNifoX
            R+IsAI8Ad7vIh0PM8uzEWMmeFWx8P9g07GMxYnBiwKRLvsxLvKmLcMl6s5/p5XMi
            dFgJUTNyP/OFsVbGajbrFqrLD1Ry+MbY4i2Es1Dw/ypem+CBO96VzrQe4SdYS90R
            mLoEssDreHnoSd6DgOvH71Rtd/I2FdruTLvV9cTfeBrhi2xjOBGVJCR25+M2o1HS
            XgFGIaUEiaDcLfWe56zzD98p2hz+lPf+21xTrtHXn1NH3Rkbj9u6qsIxZRvTqYxB
            QpEwENUCcLQtV2fQBPZCOTE/OF81o4ktoSGjXXqCQHe1H2Tx1m2MbLwLwTWsGiQ=
            =xcPN
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
