/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v2/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumServiceUpdateRequest
 */
export interface AlbumServiceUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof AlbumServiceUpdateRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumServiceUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumServiceUpdateRequest
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumServiceUpdateRequest
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof AlbumServiceUpdateRequest
     */
    publishedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AlbumServiceUpdateRequest
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the AlbumServiceUpdateRequest interface.
 */
export function instanceOfAlbumServiceUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AlbumServiceUpdateRequestFromJSON(json: any): AlbumServiceUpdateRequest {
    return AlbumServiceUpdateRequestFromJSONTyped(json, false);
}

export function AlbumServiceUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumServiceUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        '_private': !exists(json, 'private') ? undefined : json['private'],
    };
}

export function AlbumServiceUpdateRequestToJSON(value?: AlbumServiceUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'private': value._private,
    };
}

