/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaCustomProperties
 */
export interface MediaCustomProperties {
    /**
     * 
     * @type {number}
     * @memberof MediaCustomProperties
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof MediaCustomProperties
     */
    width?: number;
}

/**
 * Check if a given object implements the MediaCustomProperties interface.
 */
export function instanceOfMediaCustomProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaCustomPropertiesFromJSON(json: any): MediaCustomProperties {
    return MediaCustomPropertiesFromJSONTyped(json, false);
}

export function MediaCustomPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaCustomProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'height': !exists(json, 'height') ? undefined : json['height'],
        'width': !exists(json, 'width') ? undefined : json['width'],
    };
}

export function MediaCustomPropertiesToJSON(value?: MediaCustomProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'height': value.height,
        'width': value.width,
    };
}

