/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Protoalbumsv1CreateResponse
 */
export interface Protoalbumsv1CreateResponse {
    /**
     * 
     * @type {number}
     * @memberof Protoalbumsv1CreateResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateResponse
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateResponse
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateResponse
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof Protoalbumsv1CreateResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateResponse
     */
    authorId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Protoalbumsv1CreateResponse
     */
    _private?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateResponse
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Protoalbumsv1CreateResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Protoalbumsv1CreateResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Protoalbumsv1CreateResponse
     */
    notifyUsersOnPublished?: boolean;
}

/**
 * Check if a given object implements the Protoalbumsv1CreateResponse interface.
 */
export function instanceOfProtoalbumsv1CreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Protoalbumsv1CreateResponseFromJSON(json: any): Protoalbumsv1CreateResponse {
    return Protoalbumsv1CreateResponseFromJSONTyped(json, false);
}

export function Protoalbumsv1CreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoalbumsv1CreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'notifyUsersOnPublished': !exists(json, 'notifyUsersOnPublished') ? undefined : json['notifyUsersOnPublished'],
    };
}

export function Protoalbumsv1CreateResponseToJSON(value?: Protoalbumsv1CreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'title': value.title,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'authorId': value.authorId,
        'private': value._private,
        'userId': value.userId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'notifyUsersOnPublished': value.notifyUsersOnPublished,
    };
}

