/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Protoarticlesv1UpdateResponse
 */
export interface Protoarticlesv1UpdateResponse {
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1UpdateResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1UpdateResponse
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1UpdateResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1UpdateResponse
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1UpdateResponse
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof Protoarticlesv1UpdateResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1UpdateResponse
     */
    authorId?: string;
}

/**
 * Check if a given object implements the Protoarticlesv1UpdateResponse interface.
 */
export function instanceOfProtoarticlesv1UpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Protoarticlesv1UpdateResponseFromJSON(json: any): Protoarticlesv1UpdateResponse {
    return Protoarticlesv1UpdateResponseFromJSONTyped(json, false);
}

export function Protoarticlesv1UpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoarticlesv1UpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
    };
}

export function Protoarticlesv1UpdateResponseToJSON(value?: Protoarticlesv1UpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'name': value.name,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'authorId': value.authorId,
    };
}

