/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Protoalbumsv1CreateRequest
 */
export interface Protoalbumsv1CreateRequest {
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateRequest
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoalbumsv1CreateRequest
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof Protoalbumsv1CreateRequest
     */
    publishedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Protoalbumsv1CreateRequest
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the Protoalbumsv1CreateRequest interface.
 */
export function instanceOfProtoalbumsv1CreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Protoalbumsv1CreateRequestFromJSON(json: any): Protoalbumsv1CreateRequest {
    return Protoalbumsv1CreateRequestFromJSONTyped(json, false);
}

export function Protoalbumsv1CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoalbumsv1CreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        '_private': !exists(json, 'private') ? undefined : json['private'],
    };
}

export function Protoalbumsv1CreateRequestToJSON(value?: Protoalbumsv1CreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'private': value._private,
    };
}

