/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1AlbumResponse,
    V1AlbumResponseFromJSON,
    V1AlbumResponseFromJSONTyped,
    V1AlbumResponseToJSON,
} from './V1AlbumResponse';

/**
 * 
 * @export
 * @interface Protoalbumsv1IndexResponse
 */
export interface Protoalbumsv1IndexResponse {
    /**
     * 
     * @type {Array<V1AlbumResponse>}
     * @memberof Protoalbumsv1IndexResponse
     */
    data?: Array<V1AlbumResponse>;
}

/**
 * Check if a given object implements the Protoalbumsv1IndexResponse interface.
 */
export function instanceOfProtoalbumsv1IndexResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Protoalbumsv1IndexResponseFromJSON(json: any): Protoalbumsv1IndexResponse {
    return Protoalbumsv1IndexResponseFromJSONTyped(json, false);
}

export function Protoalbumsv1IndexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoalbumsv1IndexResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(V1AlbumResponseFromJSON)),
    };
}

export function Protoalbumsv1IndexResponseToJSON(value?: Protoalbumsv1IndexResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(V1AlbumResponseToJSON)),
    };
}

