/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1ArticleResponse,
    V1ArticleResponseFromJSON,
    V1ArticleResponseFromJSONTyped,
    V1ArticleResponseToJSON,
} from './V1ArticleResponse';

/**
 * 
 * @export
 * @interface Protoarticlesv1IndexResponse
 */
export interface Protoarticlesv1IndexResponse {
    /**
     * 
     * @type {Array<V1ArticleResponse>}
     * @memberof Protoarticlesv1IndexResponse
     */
    data: Array<V1ArticleResponse>;
}

/**
 * Check if a given object implements the Protoarticlesv1IndexResponse interface.
 */
export function instanceOfProtoarticlesv1IndexResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function Protoarticlesv1IndexResponseFromJSON(json: any): Protoarticlesv1IndexResponse {
    return Protoarticlesv1IndexResponseFromJSONTyped(json, false);
}

export function Protoarticlesv1IndexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoarticlesv1IndexResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(V1ArticleResponseFromJSON)),
    };
}

export function Protoarticlesv1IndexResponseToJSON(value?: Protoarticlesv1IndexResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(V1ArticleResponseToJSON)),
    };
}

