/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Protoarticlesv1CreateRequest
 */
export interface Protoarticlesv1CreateRequest {
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1CreateRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1CreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1CreateRequest
     */
    metaDescription: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv1CreateRequest
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof Protoarticlesv1CreateRequest
     */
    publishedAt?: Date;
}

/**
 * Check if a given object implements the Protoarticlesv1CreateRequest interface.
 */
export function instanceOfProtoarticlesv1CreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "metaDescription" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function Protoarticlesv1CreateRequestFromJSON(json: any): Protoarticlesv1CreateRequest {
    return Protoarticlesv1CreateRequestFromJSONTyped(json, false);
}

export function Protoarticlesv1CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoarticlesv1CreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': json['name'],
        'metaDescription': json['metaDescription'],
        'content': json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
    };
}

export function Protoarticlesv1CreateRequestToJSON(value?: Protoarticlesv1CreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
    };
}

