/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v2/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Protoarticlesv2CreateResponse
 */
export interface Protoarticlesv2CreateResponse {
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv2CreateResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv2CreateResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv2CreateResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv2CreateResponse
     */
    metaDescription: string;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv2CreateResponse
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof Protoarticlesv2CreateResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Protoarticlesv2CreateResponse
     */
    authorId: string;
}

/**
 * Check if a given object implements the Protoarticlesv2CreateResponse interface.
 */
export function instanceOfProtoarticlesv2CreateResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "metaDescription" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "authorId" in value;

    return isInstance;
}

export function Protoarticlesv2CreateResponseFromJSON(json: any): Protoarticlesv2CreateResponse {
    return Protoarticlesv2CreateResponseFromJSONTyped(json, false);
}

export function Protoarticlesv2CreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoarticlesv2CreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
        'metaDescription': json['metaDescription'],
        'content': json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'authorId': json['authorId'],
    };
}

export function Protoarticlesv2CreateResponseToJSON(value?: Protoarticlesv2CreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'name': value.name,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'authorId': value.authorId,
    };
}

