/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v2/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V2AlbumResponse,
    V2AlbumResponseFromJSON,
    V2AlbumResponseFromJSONTyped,
    V2AlbumResponseToJSON,
} from './V2AlbumResponse';

/**
 * 
 * @export
 * @interface Protoalbumsv2IndexResponse
 */
export interface Protoalbumsv2IndexResponse {
    /**
     * 
     * @type {Array<V2AlbumResponse>}
     * @memberof Protoalbumsv2IndexResponse
     */
    data?: Array<V2AlbumResponse>;
}

/**
 * Check if a given object implements the Protoalbumsv2IndexResponse interface.
 */
export function instanceOfProtoalbumsv2IndexResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Protoalbumsv2IndexResponseFromJSON(json: any): Protoalbumsv2IndexResponse {
    return Protoalbumsv2IndexResponseFromJSONTyped(json, false);
}

export function Protoalbumsv2IndexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Protoalbumsv2IndexResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(V2AlbumResponseFromJSON)),
    };
}

export function Protoalbumsv2IndexResponseToJSON(value?: Protoalbumsv2IndexResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(V2AlbumResponseToJSON)),
    };
}

