/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v1/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1DeleteResponse
 */
export interface V1DeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof V1DeleteResponse
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the V1DeleteResponse interface.
 */
export function instanceOfV1DeleteResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1DeleteResponseFromJSON(json: any): V1DeleteResponse {
    return V1DeleteResponseFromJSONTyped(json, false);
}

export function V1DeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
    };
}

export function V1DeleteResponseToJSON(value?: V1DeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deleted': value.deleted,
    };
}

