/* tslint:disable */
/* eslint-disable */
/**
 * proto/medias/v1/medias.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetBySlugResponse
 */
export interface V1GetBySlugResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GetBySlugResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetBySlugResponse
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetBySlugResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetBySlugResponse
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetBySlugResponse
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1GetBySlugResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1GetBySlugResponse
     */
    authorId?: string;
}

/**
 * Check if a given object implements the V1GetBySlugResponse interface.
 */
export function instanceOfV1GetBySlugResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetBySlugResponseFromJSON(json: any): V1GetBySlugResponse {
    return V1GetBySlugResponseFromJSONTyped(json, false);
}

export function V1GetBySlugResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetBySlugResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
    };
}

export function V1GetBySlugResponseToJSON(value?: V1GetBySlugResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'name': value.name,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'authorId': value.authorId,
    };
}

