/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v2/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V2Category,
    V2CategoryFromJSON,
    V2CategoryFromJSONTyped,
    V2CategoryToJSON,
} from './V2Category';
import {
    V2Media,
    V2MediaFromJSON,
    V2MediaFromJSONTyped,
    V2MediaToJSON,
} from './V2Media';

/**
 * 
 * @export
 * @interface V2AlbumResponse
 */
export interface V2AlbumResponse {
    /**
     * 
     * @type {number}
     * @memberof V2AlbumResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof V2AlbumResponse
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V2AlbumResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof V2AlbumResponse
     */
    metaDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof V2AlbumResponse
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof V2AlbumResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V2AlbumResponse
     */
    authorId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V2AlbumResponse
     */
    _private?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V2AlbumResponse
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof V2AlbumResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V2AlbumResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof V2AlbumResponse
     */
    notifyUsersOnPublished?: boolean;
    /**
     * 
     * @type {Array<V2Category>}
     * @memberof V2AlbumResponse
     */
    categories?: Array<V2Category>;
    /**
     * 
     * @type {Array<V2Media>}
     * @memberof V2AlbumResponse
     */
    medias?: Array<V2Media>;
}

/**
 * Check if a given object implements the V2AlbumResponse interface.
 */
export function instanceOfV2AlbumResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V2AlbumResponseFromJSON(json: any): V2AlbumResponse {
    return V2AlbumResponseFromJSONTyped(json, false);
}

export function V2AlbumResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2AlbumResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'notifyUsersOnPublished': !exists(json, 'notifyUsersOnPublished') ? undefined : json['notifyUsersOnPublished'],
        'categories': !exists(json, 'categories') ? undefined : ((json['categories'] as Array<any>).map(V2CategoryFromJSON)),
        'medias': !exists(json, 'medias') ? undefined : ((json['medias'] as Array<any>).map(V2MediaFromJSON)),
    };
}

export function V2AlbumResponseToJSON(value?: V2AlbumResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'slug': value.slug,
        'title': value.title,
        'metaDescription': value.metaDescription,
        'content': value.content,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'authorId': value.authorId,
        'private': value._private,
        'userId': value.userId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'notifyUsersOnPublished': value.notifyUsersOnPublished,
        'categories': value.categories === undefined ? undefined : ((value.categories as Array<any>).map(V2CategoryToJSON)),
        'medias': value.medias === undefined ? undefined : ((value.medias as Array<any>).map(V2MediaToJSON)),
    };
}

