/* tslint:disable */
/* eslint-disable */
/**
 * proto/articles/v2/articles.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2Category
 */
export interface V2Category {
    /**
     * 
     * @type {number}
     * @memberof V2Category
     */
    id?: number;
}

/**
 * Check if a given object implements the V2Category interface.
 */
export function instanceOfV2Category(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V2CategoryFromJSON(json: any): V2Category {
    return V2CategoryFromJSONTyped(json, false);
}

export function V2CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2Category {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function V2CategoryToJSON(value?: V2Category | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

