apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: databases
    spec:
      containers:
        - image: redis:5-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis
              mountPath: /data
          readinessProbe:
            periodSeconds: 30
            exec:
              command:
                - redis-cli
                - ping
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: pvc-redis
