apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  labels:
    app: redis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
