---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    service: redis
spec:
  ports:
    - name: tcp-redis
      #appProtocol: redis
      port: 6379
      protocol: TCP
  selector:
    app: redis
    tier: databases
