// Code generated by entc, DO NOT EDIT.

package ent

import (
	"api-go/ent/album"
	"api-go/ent/albumcosplayer"
	"api-go/ent/cosplayer"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlbumCosplayerCreate is the builder for creating a AlbumCosplayer entity.
type AlbumCosplayerCreate struct {
	config
	mutation *AlbumCosplayerMutation
	hooks    []Hook
}

// SetAlbumID sets the "album_id" field.
func (acc *AlbumCosplayerCreate) SetAlbumID(i int32) *AlbumCosplayerCreate {
	acc.mutation.SetAlbumID(i)
	return acc
}

// SetNillableAlbumID sets the "album_id" field if the given value is not nil.
func (acc *AlbumCosplayerCreate) SetNillableAlbumID(i *int32) *AlbumCosplayerCreate {
	if i != nil {
		acc.SetAlbumID(*i)
	}
	return acc
}

// SetCosplayerID sets the "cosplayer_id" field.
func (acc *AlbumCosplayerCreate) SetCosplayerID(i int32) *AlbumCosplayerCreate {
	acc.mutation.SetCosplayerID(i)
	return acc
}

// SetNillableCosplayerID sets the "cosplayer_id" field if the given value is not nil.
func (acc *AlbumCosplayerCreate) SetNillableCosplayerID(i *int32) *AlbumCosplayerCreate {
	if i != nil {
		acc.SetCosplayerID(*i)
	}
	return acc
}

// SetCreatedAt sets the "created_at" field.
func (acc *AlbumCosplayerCreate) SetCreatedAt(t time.Time) *AlbumCosplayerCreate {
	acc.mutation.SetCreatedAt(t)
	return acc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (acc *AlbumCosplayerCreate) SetNillableCreatedAt(t *time.Time) *AlbumCosplayerCreate {
	if t != nil {
		acc.SetCreatedAt(*t)
	}
	return acc
}

// SetUpdatedAt sets the "updated_at" field.
func (acc *AlbumCosplayerCreate) SetUpdatedAt(t time.Time) *AlbumCosplayerCreate {
	acc.mutation.SetUpdatedAt(t)
	return acc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (acc *AlbumCosplayerCreate) SetNillableUpdatedAt(t *time.Time) *AlbumCosplayerCreate {
	if t != nil {
		acc.SetUpdatedAt(*t)
	}
	return acc
}

// SetID sets the "id" field.
func (acc *AlbumCosplayerCreate) SetID(i int32) *AlbumCosplayerCreate {
	acc.mutation.SetID(i)
	return acc
}

// SetAlbum sets the "album" edge to the Album entity.
func (acc *AlbumCosplayerCreate) SetAlbum(a *Album) *AlbumCosplayerCreate {
	return acc.SetAlbumID(a.ID)
}

// SetCosplayer sets the "cosplayer" edge to the Cosplayer entity.
func (acc *AlbumCosplayerCreate) SetCosplayer(c *Cosplayer) *AlbumCosplayerCreate {
	return acc.SetCosplayerID(c.ID)
}

// Mutation returns the AlbumCosplayerMutation object of the builder.
func (acc *AlbumCosplayerCreate) Mutation() *AlbumCosplayerMutation {
	return acc.mutation
}

// Save creates the AlbumCosplayer in the database.
func (acc *AlbumCosplayerCreate) Save(ctx context.Context) (*AlbumCosplayer, error) {
	var (
		err  error
		node *AlbumCosplayer
	)
	if len(acc.hooks) == 0 {
		if err = acc.check(); err != nil {
			return nil, err
		}
		node, err = acc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AlbumCosplayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = acc.check(); err != nil {
				return nil, err
			}
			acc.mutation = mutation
			if node, err = acc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(acc.hooks) - 1; i >= 0; i-- {
			if acc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = acc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, acc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (acc *AlbumCosplayerCreate) SaveX(ctx context.Context) *AlbumCosplayer {
	v, err := acc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acc *AlbumCosplayerCreate) Exec(ctx context.Context) error {
	_, err := acc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acc *AlbumCosplayerCreate) ExecX(ctx context.Context) {
	if err := acc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acc *AlbumCosplayerCreate) check() error {
	return nil
}

func (acc *AlbumCosplayerCreate) sqlSave(ctx context.Context) (*AlbumCosplayer, error) {
	_node, _spec := acc.createSpec()
	if err := sqlgraph.CreateNode(ctx, acc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	return _node, nil
}

func (acc *AlbumCosplayerCreate) createSpec() (*AlbumCosplayer, *sqlgraph.CreateSpec) {
	var (
		_node = &AlbumCosplayer{config: acc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: albumcosplayer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: albumcosplayer.FieldID,
			},
		}
	)
	if id, ok := acc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := acc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: albumcosplayer.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := acc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: albumcosplayer.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := acc.mutation.AlbumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   albumcosplayer.AlbumTable,
			Columns: []string{albumcosplayer.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt32,
					Column: album.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AlbumID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := acc.mutation.CosplayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   albumcosplayer.CosplayerTable,
			Columns: []string{albumcosplayer.CosplayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt32,
					Column: cosplayer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CosplayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AlbumCosplayerCreateBulk is the builder for creating many AlbumCosplayer entities in bulk.
type AlbumCosplayerCreateBulk struct {
	config
	builders []*AlbumCosplayerCreate
}

// Save creates the AlbumCosplayer entities in the database.
func (accb *AlbumCosplayerCreateBulk) Save(ctx context.Context) ([]*AlbumCosplayer, error) {
	specs := make([]*sqlgraph.CreateSpec, len(accb.builders))
	nodes := make([]*AlbumCosplayer, len(accb.builders))
	mutators := make([]Mutator, len(accb.builders))
	for i := range accb.builders {
		func(i int, root context.Context) {
			builder := accb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlbumCosplayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, accb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, accb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, accb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (accb *AlbumCosplayerCreateBulk) SaveX(ctx context.Context) []*AlbumCosplayer {
	v, err := accb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (accb *AlbumCosplayerCreateBulk) Exec(ctx context.Context) error {
	_, err := accb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (accb *AlbumCosplayerCreateBulk) ExecX(ctx context.Context) {
	if err := accb.Exec(ctx); err != nil {
		panic(err)
	}
}
