# https://about.gitlab.com/2016/05/23/gitlab-container-registry/

image: docker

services:
- docker:dind

stages:
- build
- test
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/nevax/picblog:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/nevax/picblog:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .cache/pip
  - vendor/
  - node_modules

before_script:
- apk add --no-cache py-pip
- pip install docker-compose
- docker-compose version
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build:
  stage: build
  script:
  - docker-compose build

unit_test:
  stage: test
  script:
  - echo "UNIT TESTS"
  - docker-compose up -d
  - docker-compose exec php .vendor/bin/phpunit --coverage-text
  - docker-compose down
  allow_failure: true

integration_test:
  stage: test
  script:
  - echo "INTEGRATION TEST"

release_image:
  stage: release
  script:
  - docker-compose push registry.gitlab.com/nevax/picblog
#  - docker push registry.gitlab.com/nevax/picblog
#  - docker pull $CONTAINER_TEST_IMAGE
#  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#  - docker push $CONTAINER_RELEASE_IMAGE

deploy_dev:
  stage: deploy
  script:
  - echo "Deploying stagging"

deploy_production:
  stage: deploy
  script:
  - echo "Deploying production"
  only:
  - master
