# https://about.gitlab.com/2016/05/23/gitlab-container-registry/

image: docker

services:
- docker:dind

stages:
- build
- test
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/nevax/picblog:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/nevax/picblog:latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .cache/pip
  - vendor/
  - node_modules

before_script:
- apk add --no-cache py-pip
- echo "Installing Docker compose" && pip install docker-compose
- echo "Docker compose version" && docker-compose version
- echo "Docker compose validating" && docker-compose config
- echo "Login to gitlab registry" && docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build:
  stage: build
  script:
  - docker-compose build
  - docker push registry.gitlab.com/nevax/picblog/picblog_php:latest
  - docker push registry.gitlab.com/nevax/picblog/picblog_nginx:latest

unit_test:
  stage: test
  script:
  - echo "UNIT TESTS"
  - docker-compose pull
  - docker-compose up -d
  - docker-compose exec -T php apk add --no-cache $PHPIZE_DEPS && pecl install xdebug && docker-php-ext-enable xdebug
  - docker-compose exec -T php vendor/bin/phpunit --coverage-text
  - docker-compose down
  allow_failure: true

integration_test:
  stage: test
  script:
  - echo "INTEGRATION TEST"
  - docker-compose pull
  - docker-compose up -d
  - docker-compose exec -T php echo "Run test here"
  - docker-compose down

deploy_dev:
  stage: deploy
  script:
  - echo "Deploying stagging"
  - docker-compose pull

deploy_production:
  stage: deploy
  script:
  - echo "Deploying production"
  - docker-compose pull
  only:
  - master
