image: docker

stages:
- build
- test

services:
- docker:dind

before_script:
- apk add --no-cache py-pip
- pip install docker-compose
- docker-compose version

build:
  stage: build
  script:
  - docker login registry.gitlab.com
  - docker-compose build -t registry.gitlab.com/nevax/picblog .
  - docker push registry.gitlab.com/nevax/picblog

test:
  stage: test
  script:
  - echo "TEST"
  - docker-compose up -d
  - docker-compose exec php .vendor/bin/phpunit --coverage-text
  - docker-compose down
  allow_failure: true
