version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
    - src:/var/www/html
    links:
    - db

  db:
    image: mariadb
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=picblog
    - MYSQL_USER=picblog
    - MYSQL_PASSWORD=secret

  web:
    image: nginx:alpine
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - src:/var/www/html
    - ./docker/php-fpm/site.conf:/etc/nginx/conf.d/default.conf
    links:
    - php

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  links:
  #  - mysql:db
  #  ports:
  #  - "8082:80"
  #  environment:
  #  - PMA_USER=picblog
  #  - PMA_PASSWORD=secret
  #  - PHP_UPLOAD_MAX_FILESIZE=100MB

volumes:
  db-data:
  src: