version: '3.4'

services:
  db:
    image: mariadb
    restart: always
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=picblog
    - MYSQL_USER=picblog
    - MYSQL_PASSWORD=secret

  php:
    image: registry.gitlab.com/nevax/picblog/picblog_php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      cache_from:
      - registry.gitlab.com/nevax/picblog/picblog_php:latest
    restart: always
    volumes:
    - storage:/var/www/html/storage
    - public_vendor:/var/www/html/public/vendor
    links:
    - db
    - cache
    depends_on:
    - db
    - cache

  nginx:
    image: registry.gitlab.com/nevax/picblog/picblog_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      cache_from:
        - registry.gitlab.com/nevax/picblog/picblog_nginx:latest
    restart: always
    ports:
    - 8080:80
    - 4434:443
    env_file: ./docker/nginx/.env.production
    volumes:
    - storage:/var/www/html/storage:ro
    - public_vendor:/var/www/html/public/vendor:ro
    links:
    - php
    depends_on:
    - php

  cache:
    image: redis:5.0-alpine

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
    - db
    ports:
    - "8082:80"
    environment:
    - PHP_UPLOAD_MAX_FILESIZE=100MB

volumes:
  db-data:
  storage:
  public_vendor:
