version: '3.7'
services:

  nginx:
    ports:
    - "8080:80"

  cache:
    image: redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - cache_data:/data:rw,delegated

  db_pg:
    image: postgres:11-alpine
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - db-pg-data:/var/lib/postgresql/data:rw,delegated
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgbackups3:
    image: itbm/postgresql-backup-s3 # fork of schickling/postgres-backup-s3
    depends_on:
      - db_pg
    links:
      - db_pg
    environment:
      S3_ACCESS_KEY_ID: ${DO_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${DO_SECRET_ACCESS_KEY}
      S3_BUCKET: ${DO_BUCKET}
      S3_PREFIX: ${HOSTNAME}/backups
      S3_ENDPOINT: ${DO_ENDPOINT}
      POSTGRES_HOST: db_pg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: '@daily'
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'

volumes:
  cache_data:
  db-pg-data:

networks:
  default:
    external:
      name: database-network
