version: '3.7'
services:

  nginx:
    ports:
    - "8080:80"

  cache:
    image: redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - cache_data:/data:rw,delegated

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - db-pg-data:/var/lib/postgresql/data:rw,delegated
    environment:
      POSTGRES_DB: flasher_testing
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret

volumes:
  cache_data:
  db-pg-data:

