version: '3.7'
services:

  php: &php_base
    image: registry.gitlab.com/flasher/flasher/picblog_php:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: php_app
    restart: unless-stopped
    networks:
      - database-network
      - backend
    volumes:
      - storage:/var/www/html/storage:rw,delegated
      - public_vendor:/var/www/html/public/vendor:rw,delegated
    environment: &php_environment
      COMMIT_SHORT_SHA: "${CI_COMMIT_SHORT_SHA}"
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "${APP_URL}"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_DATABASE: "flasher"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USERNAME: "admin"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: "cache"
      BROADCAST_DRIVER: "redis"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      SESSION_LIFETIME: "120"
      SESSION_SECURE_COOKIE: "true"
      MAIL_DRIVER: "${MAIL_DRIVER}"
      SES_KEY: "${SES_KEY}"
      SES_SECRET: "${SES_SECRET}"
      SES_REGION: "${SES_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_DEFAULT_REGION: "${S3_DEFAULT_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_BUCKET_CDN: "${S3_BUCKET_CDN}"
      NOCAPTCHA_SECRET: "${NOCAPTCHA_SECRET}"
      NOCAPTCHA_SITEKEY: "${NOCAPTCHA_SITEKEY}"
      TELESCOPE_ENABLED: "false"
      SENTRY_LARAVEL_DSN: "${SENTRY_LARAVEL_DSN}"
      #TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      TRUSTED_PROXIES: "*"
      ANALYTICS_PROVIDER: "GoogleAnalytics"
      ANALYTICS_TRACKING_ID: "${ANALYTICS_TRACKING_ID_PROD}"
      SLACK_WEBHOOK_URL: "${SLACK_WEBHOOK_URL}"
      MIX_SENTRY_DSN_PUBLIC: "${FRONT_SENTRY_DSN_PUBLIC}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${APP_NAME}"

  queue:
    <<: *php_base
    environment:
      <<: *php_environment
      CONTAINER_ROLE: "queue"

  scheduler:
    <<: *php_base
    user: root
    environment:
      <<: *php_environment
      CONTAINER_ROLE: "scheduler"

  publisher:
    <<: *php_base
    restart: on-failure
    environment:
      <<: *php_environment
      CONTAINER_ROLE: "publisher"

  nginx:
    image: registry.gitlab.com/flasher/flasher/picblog_nginx:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    restart: unless-stopped
    expose:
      - 80
    networks:
      - nginx-proxy
      - backend
    environment:
      NGINX_HOST: ${APP_URI}
      ERROR_LOG_LEVEL: ${ERROR_LOG_LEVEL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-proxy"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-insecure.rule=Host(`${APP_URL}`) || Host(`www.${APP_URL}`)"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-insecure.entrypoints=web"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-insecure.middlewares=flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-redirect-non-www,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-https-only,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-limit,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-test-ratelimit,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-retry,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-error-check,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-compress"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}.rule=Host(`${APP_URL}`) || Host(`www.${APP_URL}`)"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}.entrypoints=websecure"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}.middlewares=flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-redirect-non-www,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-https-only,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-limit,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-test-ratelimit,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-retry,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-error-check,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-hsts,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-frame,flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-compress"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-hsts.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-hsts.headers.stsPreload=true"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-hsts.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-frame.headers.frameDeny=true"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-compress.compress=true"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-https-only.redirectscheme.scheme=https"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-https-only.redirectscheme.permanent=true"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-retry.retry.attempts=4"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-error-check.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.30 || NetworkErrorRatio() > 0.10"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-limit.buffering.maxRequestBodyBytes=10000000" # 10 Mb
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-limit.buffering.memResponseBodyBytes=10000000" # 10 Mb
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-test-ratelimit.ratelimit.average=1000"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-test-ratelimit.ratelimit.burst=500"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-redirect-non-www.redirectregex.regex=^https?://www.${APP_URL}/(.*)"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-redirect-non-www.redirectregex.replacement=https://${APP_URL}/$${1}"
      - "traefik.http.middlewares.flasher-${APP_ENV}-${CI_COMMIT_REF_NAME}-redirect-non-www.redirectregex.permanent=true"
    volumes:
      - storage:/var/www/html/storage:ro,delegated
      - public_vendor:/var/www/html/public/vendor:ro,delegated
    depends_on:
      - php

volumes:
  storage:
  public_vendor:

networks:
  backend:
  nginx-proxy:
    external: true
  database-network:
    external: true
