version: '3.7'
services:

  tusd:
    image: tusproject/tusd
    networks:
      - backend
      - nginx-proxy
    command: -base-path /tus/ -behind-proxy -hooks-http http://nginx/api/admin/album-media-added -hooks-http-retry 5 -hooks-http-backoff 2 -hooks-enabled-events post-finish,pre-create
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-tusd.rule=(Host(`${APP_URI}`) && PathPrefix(`/tus`)) || (Host(`www.${APP_URI}`) && PathPrefix(`/tus`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-tusd.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-tusd.middlewares=${COMPOSE_PROJECT_NAME}-tusd-retry,${COMPOSE_PROJECT_NAME}-tusd-error-check,${COMPOSE_PROJECT_NAME}-tusd-headers,${COMPOSE_PROJECT_NAME}-tusd-compress"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-tusd.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT,PATCH,DELETE"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.accessControlMaxAge=63072000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.accessControlAllowHeaders=Authorization,Origin,Content-Type,Accept,tus-resumable,upload-length,upload-metadata,upload-offset"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.addVaryHeader=true"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-headers.headers.sslProxyHeaders=https"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-compress.compress=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-retry.retry.attempts=4"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-error-check.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.30 || NetworkErrorRatio() > 0.10"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-limit.buffering.maxRequestBodyBytes=20000000" # 20 Mb
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-limit.buffering.memResponseBodyBytes=20000000" # 20 Mb
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-ratelimit.ratelimit.average=1000"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-tusd-ratelimit.ratelimit.burst=500"

  php: &php_base
    image: registry.gitlab.com/flasher/flasher/picblog_php:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: php_app
    restart: unless-stopped
    networks:
      - database-network
      - backend
    volumes:
      - storage:/var/www/html/storage:rw,delegated
      - public_vendor:/var/www/html/public/vendor:rw,delegated
    environment: &php_environment
      COMMIT_SHORT_SHA: "${CI_COMMIT_SHORT_SHA}"
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "${APP_URL}"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_DATABASE: "flasher"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USERNAME: "admin"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: "cache"
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-redis}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      QUEUE_DRIVER: ${QUEUE_DRIVER:-redis}
      SESSION_LIFETIME: "120"
      SESSION_SECURE_COOKIE: "true"
      MAIL_MAILER: "${MAIL_MAILER}"
      SES_KEY: "${SES_KEY}"
      SES_SECRET: "${SES_SECRET}"
      SES_REGION: "${SES_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_DEFAULT_REGION: "${S3_DEFAULT_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_BUCKET_CDN: "${S3_BUCKET_CDN}"
      NOCAPTCHA_SECRET: "${NOCAPTCHA_SECRET}"
      NOCAPTCHA_SITEKEY: "${NOCAPTCHA_SITEKEY}"
      TELESCOPE_ENABLED: ${TELESCOPE_ENABLED:-false}
      SENTRY_LARAVEL_DSN: "${SENTRY_LARAVEL_DSN}"
      #TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      TRUSTED_PROXIES: "*"
      ANALYTICS_PROVIDER: "GoogleAnalytics"
      ANALYTICS_TRACKING_ID: "${ANALYTICS_TRACKING_ID_PROD}"
      SLACK_WEBHOOK_URL: "${SLACK_WEBHOOK_URL}"
      MIX_SENTRY_DSN_PUBLIC: "${FRONT_SENTRY_DSN_PUBLIC}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${APP_NAME}"
      SCOUT_QUEUE: ${SCOUT_QUEUE:-false}
      ALGOLIA_APP_ID: "${ALGOLIA_APP_ID}"
      ALGOLIA_SECRET: "${ALGOLIA_SECRET}"
      ENABLED_CLOUDFRONT_MEDIA_SIGNED_URL: "${ENABLED_CLOUDFRONT_MEDIA_SIGNED_URL}"
      CLOUDFRONT_KEY_PAIR_ID: "${CLOUDFRONT_KEY_PAIR_ID}"
      CLOUDFRONT_PRIVATE_KEY: "${CLOUDFRONT_PRIVATE_KEY}"
      ADMIN_URL: "${ADMIN_URL}"

  queue:
    <<: *php_base
    environment:
      <<: *php_environment
      CONTAINER_ROLE: "queue"

  scheduler:
    <<: *php_base
    user: root
    environment:
      <<: *php_environment
      CONTAINER_ROLE: "scheduler"

  publisher:
    <<: *php_base
    restart: on-failure
    environment:
      <<: *php_environment
      CONTAINER_ROLE: "publisher"

  nginx:
    image: registry.gitlab.com/flasher/flasher/picblog_nginx:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    restart: unless-stopped
    expose:
      - 80
    networks:
      - nginx-proxy
      - backend
    environment:
      NGINX_HOST: ${APP_URI}
      ERROR_LOG_LEVEL: ${ERROR_LOG_LEVEL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nginx-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${APP_URI}`) || Host(`www.${APP_URI}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}-headers,${COMPOSE_PROJECT_NAME}-ratelimit,${COMPOSE_PROJECT_NAME}-retry,${COMPOSE_PROJECT_NAME}-error-check,${COMPOSE_PROJECT_NAME}-compress"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT,PATCH,DELETE"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlMaxAge=63072000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.addVaryHeader=true"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.sslProxyHeaders=https"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-compress.compress=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-retry.retry.attempts=4"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-error-check.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.60 || NetworkErrorRatio() > 0.10"
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-limit.buffering.maxRequestBodyBytes=50000000" # 50 Mb
      #- "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-limit.buffering.memResponseBodyBytes=50000000" # 50 Mb
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-ratelimit.ratelimit.average=1000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-ratelimit.ratelimit.burst=500"
    volumes:
      - storage:/var/www/html/storage:ro,delegated
      - public_vendor:/var/www/html/public/vendor:ro,delegated
    depends_on:
      - php

volumes:
  storage:
  public_vendor:

networks:
  backend:
  nginx-proxy:
    external: true
  database-network:
    external: true
