---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  # serviceName: postgres-exporter
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
        tier: monitoring
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  key: DATA_SOURCE_NAME
                  name: postgres-exporter
            - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES 
              value: "true"
