import Vue from 'vue';
import Buefy from 'buefy';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faBell, faEdit, faStickyNote } from '@fortawesome/free-regular-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faArrowUp,
    faBook,
    faCheck,
    faChevronCircleLeft,
    faCog,
    faExclamationCircle,
    faExternalLinkAlt,
    faImages,
    faInfo,
    faLock,
    faPenFancy,
    faPlus,
    faSearch,
    faSignInAlt,
    faTachometerAlt,
    faTag,
    faTags,
    faTasks,
    faTrashAlt,
    faUpload,
    faUserTag,
    faLink,
    faEye,
    faDownload,
    faEnvelope,
    faHeart,
    faHome,
    faKey,
    faSadTear,
    faUser,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faImages,
    faTags,
    faUserTag,
    faPenFancy,
    faBook,
    faTachometerAlt,
    faTasks,
    faChevronCircleLeft,
    faAngleDown,
    faCheck,
    faSearch,
    faPlus,
    faLock,
    faTrashAlt,
    faExternalLinkAlt,
    faUpload,
    faSignInAlt,
    faAngleRight,
    faAngleLeft,
    faArrowUp,
    faTag,
    faInfo,
    faCog,
    faExclamationCircle,
    faBell,
    faStickyNote,
    faEdit,
    faLink,
    faEye,
    faDownload,
    faEnvelope,
    faHeart,
    faHome,
    faKey,
    faSadTear,
    faUser
);

Vue.component('vue-fontawesome', FontAwesomeIcon);

Vue.use(Buefy, {
    defaultIconComponent: 'vue-fontawesome',
    defaultIconPack: 'fas',
});
