apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: api-scheduler
spec:
  concurrencyPolicy: Replace
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-scheduler
              image: php
              imagePullPolicy: IfNotPresent
              env:
                - name: CONTAINER_ROLE
                  value: scheduler
              envFrom:
                - configMapRef:
                    name: api-config
          restartPolicy: OnFailure
