apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: public-storage
          emptyDir: {} # Persistent ?
        - name: media-library
          emptyDir: {} # Persistent ?
        - name: public-vendor
          emptyDir: {}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "php" # Alias for nginx to point to php container
      imagePullSecrets:
        - name: gitlab-registry
      enableServiceLinks: false
      containers:
        - image: nginx
          name: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: public-storage
              mountPath: /var/www/html/storage/app/public
            - name: public-vendor
              mountPath: /var/www/html/public/vendor
          env:
            - name: ERROR_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: log.level
          ports:
            - name: nginx-web
              containerPort: 80
          readinessProbe:
            periodSeconds: 10
            httpGet:
              path: /api/monitor
              port: 80
        - image: php
          name: php
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: public-storage
              mountPath: /var/www/html/storage/app/public
            - name: public-vendor
              mountPath: /var/www/html/public/vendor
            - name: media-library
              mountPath: /var/www/html/storage/media-library
          env:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKeyId
                  name: s3-assets
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretAccessKey
                  name: s3-assets
            - name: S3_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: s3-assets
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: bucket
                  name: s3-assets
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: s3-assets
            - name: S3_BUCKET_CDN
              valueFrom:
                secretKeyRef:
                  key: cdn
                  name: s3-assets
            - name: SES_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: ses
            - name: SES_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: ses
            - name: SES_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: ses
            - name: ANALYTICS_TRACKING_ID
              valueFrom:
                secretKeyRef:
                  key: trackingId
                  name: google-analytics
          envFrom:
            - secretRef:
                name: api-secret
            - configMapRef:
                name: api-config
          ports:
            - name: php-fpm
              containerPort: 9000
        - image: php
          name: worker
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: public-storage
              mountPath: /var/www/html/storage/app/public
            - name: public-vendor
              mountPath: /var/www/html/public/vendor
            - name: media-library
              mountPath: /var/www/html/storage/media-library
          env:
            - name: CONTAINER_ROLE
              value: queue
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKeyId
                  name: s3-assets
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretAccessKey
                  name: s3-assets
            - name: S3_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: s3-assets
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  key: bucket
                  name: s3-assets
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: s3-assets
            - name: S3_BUCKET_CDN
              valueFrom:
                secretKeyRef:
                  key: cdn
                  name: s3-assets
            - name: SES_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: ses
            - name: SES_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: ses
            - name: SES_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: ses
            - name: ANALYTICS_TRACKING_ID
              valueFrom:
                secretKeyRef:
                  key: trackingId
                  name: google-analytics
          envFrom:
            - secretRef:
                name: api-secret
            - configMapRef:
                name: api-config
