// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlbumCategory = "album_category"

// AlbumCategory mapped from table <album_category>
type AlbumCategory struct {
	ID         string     `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	AlbumID    string     `gorm:"column:album_id;type:;not null" json:"album_id"`
	CategoryID string     `gorm:"column:category_id;type:;not null" json:"category_id"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
}

// TableName AlbumCategory's table name
func (*AlbumCategory) TableName() string {
	return TableNameAlbumCategory
}
