// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID              string  `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	Slug            *string `gorm:"column:slug;type:" json:"slug"`
	Name            *string `gorm:"column:name;type:" json:"name"`
	MetaDescription *string `gorm:"column:meta_description;type:" json:"meta_description"`
	Content         *string `gorm:"column:content;type:" json:"content"`
	AuthorUUID      *string `gorm:"column:author_uuid;type:" json:"author_uuid"`
	PublishedAt     *string `gorm:"column:published_at;type:" json:"published_at"`
	CreatedAt       *string `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt       *string `gorm:"column:updated_at;type:" json:"updated_at"`
	DeletedAt       *string `gorm:"column:deleted_at;type:" json:"deleted_at"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
