// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategorizable = "categorizables"

// Categorizable mapped from table <categorizables>
type Categorizable struct {
	CategoryID        string     `gorm:"column:category_id;type:;not null" json:"category_id"`
	CategorizableType string     `gorm:"column:categorizable_type;type:;not null" json:"categorizable_type"`
	CategorizableID   string     `gorm:"column:categorizable_id;type:;not null" json:"categorizable_id"`
	CreatedAt         *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
}

// TableName Categorizable's table name
func (*Categorizable) TableName() string {
	return TableNameCategorizable
}
