// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCosplayer = "cosplayers"

// Cosplayer mapped from table <cosplayers>
type Cosplayer struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;type:character varying(255);not null;uniqueIndex:cosplayers_name_unique,priority:1" json:"name"`
	Slug        string     `gorm:"column:slug;type:character varying(255);not null;uniqueIndex:cosplayers_slug_unique,priority:1" json:"slug"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
	Picture     *string    `gorm:"column:picture;type:character varying(255)" json:"picture"`
	UserID      *int64     `gorm:"column:user_id;type:bigint" json:"user_id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp(0) without time zone" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp(0) without time zone" json:"updated_at"`
	SsoID       *string    `gorm:"column:sso_id;type:uuid" json:"sso_id"`
	Albums      []Album    `gorm:"joinForeignKey:CosplayerID;joinReferences:AlbumID;many2many:album_cosaplyer" json:"albums"`
}

// TableName Cosplayer's table name
func (*Cosplayer) TableName() string {
	return TableNameCosplayer
}
