// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCosplayer = "cosplayers"

// Cosplayer mapped from table <cosplayers>
type Cosplayer struct {
	ID          string     `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;type:;not null" json:"name"`
	Slug        string     `gorm:"column:slug;type:;not null" json:"slug"`
	Description *string    `gorm:"column:description;type:" json:"description"`
	Picture     *string    `gorm:"column:picture;type:" json:"picture"`
	UserID      *string    `gorm:"column:user_id;type:" json:"user_id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
	SsoID       *string    `gorm:"column:sso_id;type:" json:"sso_id"`
}

// TableName Cosplayer's table name
func (*Cosplayer) TableName() string {
	return TableNameCosplayer
}
