// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFailedJob = "failed_jobs"

// FailedJob mapped from table <failed_jobs>
type FailedJob struct {
	ID         string    `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	Connection string    `gorm:"column:connection;type:;not null" json:"connection"`
	Queue      string    `gorm:"column:queue;type:;not null" json:"queue"`
	Payload    string    `gorm:"column:payload;type:;not null" json:"payload"`
	Exception  string    `gorm:"column:exception;type:;not null" json:"exception"`
	FailedAt   time.Time `gorm:"column:failed_at;type:;not null;default:CURRENT_TIMESTAMP" json:"failed_at"`
}

// TableName FailedJob's table name
func (*FailedJob) TableName() string {
	return TableNameFailedJob
}
