// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMedium = "media"

// Medium mapped from table <media>
type Medium struct {
	ID               string     `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	ModelType        string     `gorm:"column:model_type;type:;not null" json:"model_type"`
	ModelID          string     `gorm:"column:model_id;type:;not null" json:"model_id"`
	CollectionName   string     `gorm:"column:collection_name;type:;not null" json:"collection_name"`
	Name             string     `gorm:"column:name;type:;not null" json:"name"`
	FileName         string     `gorm:"column:file_name;type:;not null" json:"file_name"`
	MimeType         *string    `gorm:"column:mime_type;type:" json:"mime_type"`
	Disk             string     `gorm:"column:disk;type:;not null" json:"disk"`
	Size             string     `gorm:"column:size;type:;not null" json:"size"`
	Manipulations    string     `gorm:"column:manipulations;type:;not null" json:"manipulations"`
	CustomProperties string     `gorm:"column:custom_properties;type:;not null" json:"custom_properties"`
	ResponsiveImages string     `gorm:"column:responsive_images;type:;not null" json:"responsive_images"`
	OrderColumn      *string    `gorm:"column:order_column;type:" json:"order_column"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
	UUID             *string    `gorm:"column:uuid;type:" json:"uuid"`
	ConversionsDisk  *string    `gorm:"column:conversions_disk;type:" json:"conversions_disk"`
}

// TableName Medium's table name
func (*Medium) TableName() string {
	return TableNameMedium
}
