// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePage = "pages"

// Page mapped from table <pages>
type Page struct {
	ID          string     `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;type:;not null" json:"name"`
	Title       string     `gorm:"column:title;type:;not null" json:"title"`
	Description *string    `gorm:"column:description;type:" json:"description"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
}

// TableName Page's table name
func (*Page) TableName() string {
	return TableNamePage
}
