// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "posts"

// Post mapped from table <posts>
type Post struct {
	ID        string     `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	Title     string     `gorm:"column:title;type:;not null" json:"title"`
	Slug      string     `gorm:"column:slug;type:;not null" json:"slug"`
	SeoTitle  *string    `gorm:"column:seo_title;type:" json:"seo_title"`
	Body      string     `gorm:"column:body;type:;not null" json:"body"`
	Active    string     `gorm:"column:active;type:;not null;default:false" json:"active"`
	UserID    *string    `gorm:"column:user_id;type:" json:"user_id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
	SsoID     string     `gorm:"column:sso_id;type:;not null" json:"sso_id"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
