// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTelescopeEntriesTag = "telescope_entries_tags"

// TelescopeEntriesTag mapped from table <telescope_entries_tags>
type TelescopeEntriesTag struct {
	EntryUUID string `gorm:"column:entry_uuid;type:;not null" json:"entry_uuid"`
	Tag       string `gorm:"column:tag;type:;not null" json:"tag"`
}

// TableName TelescopeEntriesTag's table name
func (*TelescopeEntriesTag) TableName() string {
	return TableNameTelescopeEntriesTag
}
