// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTestimonial = "testimonials"

// Testimonial mapped from table <testimonials>
type Testimonial struct {
	ID          string     `gorm:"column:id;type:;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;type:;not null" json:"name"`
	Email       string     `gorm:"column:email;type:;not null" json:"email"`
	Body        string     `gorm:"column:body;type:;not null" json:"body"`
	PublishedAt *time.Time `gorm:"column:published_at;type:" json:"published_at"`
	UserID      *string    `gorm:"column:user_id;type:" json:"user_id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
	SsoID       *string    `gorm:"column:sso_id;type:" json:"sso_id"`
}

// TableName Testimonial's table name
func (*Testimonial) TableName() string {
	return TableNameTestimonial
}
