// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsersSave = "users_save"

// UsersSave mapped from table <users_save>
type UsersSave struct {
	ID                     string     `gorm:"column:id;type:;not null" json:"id"`
	Name                   string     `gorm:"column:name;type:;not null" json:"name"`
	Email                  string     `gorm:"column:email;type:;not null" json:"email"`
	Password               string     `gorm:"column:password;type:;not null" json:"password"`
	Role                   string     `gorm:"column:role;type:;not null;default:'user'::character varying" json:"role"`
	EmailVerifiedAt        *time.Time `gorm:"column:email_verified_at;type:" json:"email_verified_at"`
	RememberToken          *string    `gorm:"column:remember_token;type:" json:"remember_token"`
	CreatedAt              *time.Time `gorm:"column:created_at;type:" json:"created_at"`
	UpdatedAt              *time.Time `gorm:"column:updated_at;type:" json:"updated_at"`
	NotifyOnAlbumPublished string     `gorm:"column:notify_on_album_published;type:;not null;default:true" json:"notify_on_album_published"`
}

// TableName UsersSave's table name
func (*UsersSave) TableName() string {
	return TableNameUsersSave
}
