// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Category struct {
	ent.Schema
}

func (Category) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.String("name").Unique(), field.String("slug").Unique(), field.String("description").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional(), field.String("meta_description")}
}
func (Category) Edges() []ent.Edge {
	return []ent.Edge{edge.To("album_categories", AlbumCategory.Type)}
}
func (Category) Annotations() []schema.Annotation {
	return nil
}
