// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Cosplayer struct {
	ent.Schema
}

func (Cosplayer) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.String("name").Unique(), field.String("slug").Unique(), field.String("description").Optional(), field.String("picture").Optional(), field.Int("user_id").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (Cosplayer) Edges() []ent.Edge {
	return []ent.Edge{edge.To("album_cosplayers", AlbumCosplayer.Type)}
}
func (Cosplayer) Annotations() []schema.Annotation {
	return nil
}
