// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Setting struct {
	ent.Schema
}

func (Setting) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("name"), field.String("value").Optional(), field.String("title"), field.String("description").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional(), field.String("type")}
}
func (Setting) Edges() []ent.Edge {
	return nil
}
func (Setting) Annotations() []schema.Annotation {
	return nil
}
