namespace: flasher-staging

patchesJson6902:
  # Change certificate secret key
  - target:
      kind: Gateway
      name: flasher-gateway
      version: v1beta1
      group: networking.istio.io
    patch: |-
      - op: replace
        path: /spec/servers/1/tls/credentialName
        value: ingress-cert-wildcard-agravelot.eu
  - target:
      kind: Gateway
      name: flasher-gateway
      version: v1beta1
      group: networking.istio.io
    patch: |-
      - op: replace
        path: /spec/servers/1/port/name
        value: https-flasher-staging # Change name to avoid conflicts https://istio.io/latest/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway
      - op: replace
        path: /spec/servers/0/port/name
        value: http-flasher-staging # Change name to avoid conflicts https://istio.io/latest/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway
      - op: replace
        path: /spec/servers/1/hosts
        value:
          - "./agravelot.eu"
          - "./*.agravelot.eu"
generators:
  - secret-generator.yml

patchesStrategicMerge:
  - api/authorization-policy.yml
  - api/virtualservice.yml
  - tusd/authorization-policy.yml
  - tusd/virtualservice.yml
  - keycloak/virtualservice.yml
  - frontend/virtualservice.yml

resources:
  - ../../base/flasher

configMapGenerator:
  - name: api-config
    literals:
      - APP_NAME=JKanda
      - APP_ENV=staging
      - APP_DEBUG="false"
      - APP_URL=https://api.agravelot.eu
      - FRONTEND_URL=https://agravelot.eu
      - ADMIN_URL=https://admin.agravelot.eu
      - BROADCAST_DRIVER=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - SCOUT_DRIVER=algolia
      - SCOUT_QUEUE=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_CONNECTION=pgsql
      - DB_DATABASE=flasher
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - LOG_CHANNEL=stderr
      - KEYCLOAK_URL=https://accounts.agravelot.eu
      - KEYCLOAK_BASE_URL=https://accounts.agravelot.eu/auth
      - KEYCLOAK_REALM=jkanda
      - KEYCLOAK_CLIENT_ID=flasher
      - KEYCLOAK_VERIFY_SSL=false
      - TELESCOPE_ENABLED=false
      - ANALYTICS_PROVIDER=GoogleAnalytics
      - MAIL_FROM_ADDRESS=contact@agravelot.eu
      - MAIL_FROM_NAME=JKanda
      - MAIL_MAILER=ses
      - SESSION_LIFETIME=120
      - SESSION_SECURE_COOKIE="true"
      - RESPONSE_CACHE_ENABLED="false"
      - TUSD_ENDPOINT=http://tusd:1080

  - name: nginx-config
    literals:
      - log.level="debug"

  - name: keycloak-config
    literals:
      - database.vendor=POSTGRES
      - database.name=keycloak
      - database.host=postgres

  - name: admin-config
    literals:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=80
      - REMOTE_API=https://api.agravelot.eu
      - KEYCLOAK_REMOTE_HOST=https://accounts.agravelot.eu # TODO Remove
      - KEYCLOAK_HOST=https://accounts.agravelot.eu
      - KEYCLOAK_REALM=jkanda
      - KEYCLOAK_CLIENT_ID=flasher
      #- DEBUG=nuxt:*

  - name: frontend-config
    literals:
      - NEXT_PUBLIC_APP_URL=https://agravelot.eu
      - NEXT_PUBLIC_API_URL=https://api.agravelot.eu/api
      - NEXT_PUBLIC_KEYCLOAK_REALM=jkanda
      - NEXT_PUBLIC_KEYCLOAK_URL=https://accounts.agravelot.eu/auth
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=flasher
      - NEXT_PUBLIC_ADMINISTRATION_URL=https://admin.agravelot.eu
      - REMOTE_API=https://api.agravelot.eu/api
      - KEYCLOAK_HOST=https://accounts.agravelot.eu
      - KEYCLOAK_REALM=jkanda
      - KEYCLOAK_CLIENT_ID=flasher
      - APP_URL=https://agravelot.eu
      - ADMIN_URL=https://admin.agravelot.eu
      - NODE_ENV=staging

images:
  - name: nginx
    newName: registry.gitlab.com/flasher/flasher/picblog_nginx
    newTag: "bca71d9"
  - name: php
    newName: registry.gitlab.com/flasher/flasher/picblog_php
    newTag: "bca71d9"
  - name: postgres
    newTag: 14-alpine
  - name: tusd
    newName: docker.io/tusproject/tusd
    newTag: v1.6.0
  - name: keycloak
    newName: registry.gitlab.com/flasher/flasher/keycloak
    newTag: 1.7.2
  - name: admin
    newName: registry.gitlab.com/flasher/flasher/flasher-admin
    newTag: "e97738f"
  - name: frontend
    newName: registry.gitlab.com/flasher/flasher/flasher-frontend
    newTag: 1.11.2
  - name: api-v2
    newName: registry.gitlab.com/flasher/flasher/flasher-api-go
    newTag: 1.7.2