apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    NOCAPTCHA_SECRET: ENC[AES256_GCM,data:LsGxc8qTF+QrHFFAWZTn0n6KkkpURSmI70YiDKuA3so7iljLzaHSBA==,iv:VbHBiVZPWyG30WR585HhvLv8Exr6z40GIL1L+qTYnRY=,tag:+uYXz2/EArpMCgYiILrl2w==,type:str]
    NOCAPTCHA_SITEKEY: ENC[AES256_GCM,data:JwbR6b/pJO7uOYijGNzqVYAnmXfOVJ/wA++bPMccdodbKNg4/m7cyQ==,iv:S4KwNPZnJ54Ep4iXw3sL1Sh/IxhnxdE5zIqZa1HNgUg=,tag:i9hUeuHs2YH6s0ICEUUr+g==,type:str]
    SENTRY_LARAVEL_DSN: ENC[AES256_GCM,data:U6J0RgtfsWPqo7sY6/Qj7/upWYd6N+kRXBJmRYts4WASqx8ZLEm1N0MvHQKglxesbVeDFo6wE6iZZEV8dKqWkZqNsOshFj+5Vw==,iv:l/wOA4Jb4h+YeNbuI1U4uZLgjldSuHsDvIpwQxNDaLE=,tag:ZOoN7zk7r1SC0lzlNTkzBA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:EPvVpzf85aoDEq3CbUiQUq0fz91UG4f+LZ7hLkETsNb/3Tx+qDHv+Wj2Y+mMQzzAJ62P,iv:RNZEOvE8iVq0DBz2Eo8/RjUrQ/v9XjQ+SrwDty5Ct/g=,tag:sMBN8JIr/WZMQbybGFHoDA==,type:str]
    KEYCLOAK_MASTER_USERNAME: ENC[AES256_GCM,data:k+Tq6F0=,iv:AKQEpFKybgxDUIqGQT6H8/FphdmDjwAnOR+91nEOtT8=,tag:R1/LUZobkZEzJL4tI8doJA==,type:str]
    KEYCLOAK_MASTER_PASSWORD: ENC[AES256_GCM,data:hNvh5rqznznG0QXwhsNG7EewaM8=,iv:djnMl09+Cx8KYgej4bKUPquomw6WE0glmnH9Uyi+Wc4=,tag:L6rlyL6pyxzT6yj+ZVcj/Q==,type:str]
    ALGOLIA_APP_ID: ENC[AES256_GCM,data:eSLuj7p1CffZtw==,iv:Iiw92sZF4fDjgKX6B48qxcmTybyFBFp5lv9Fsq5QqKY=,tag:mmANwi+7IR5455Fn1jO3PQ==,type:str]
    ALGOLIA_SECRET: ENC[AES256_GCM,data:hosfcH2DHQmJZWEpm1f2yh2hg1iZ91bpBV9mMRX032w=,iv:32wKNbY0qrNaF8MWY8DypjcZ6eHuuHIeuJntsxfF/aM=,tag:velAx8Z5sWQmIp5hdLG4zQ==,type:str]
    CRISP_WEBSITE_ID: ENC[AES256_GCM,data:8wzUSMgaAk1MeQRidb75MpemD0pQgSiZsjDC4CwMAVybrGTd,iv:CioMuYdMLdhK8+DdCghel4ZwnRs7DmNUxPxO0xLCkSk=,tag:3ZRlihHybILY5AY+mEYmPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:bFITFsY=,iv:z2TTuuUOoI2Fmx0XXyLCjUdfoM0kTpHZHtyD7ZeiKF0=,tag:b/yVOCs8Ju8AqluyA0UStg==,type:str]
    password: ENC[AES256_GCM,data:r2OvGLk=,iv:i4n9vFCh4lP+ABvaHGYyXui9FAF1hfmIDZ/8kEHnazg=,tag:/XfyK7wdBxru1tEUIojDAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:X0Lp1Tc=,iv:7Gvy2jNFKd826mzme7BBh/avBd/iopGEVkrfLLZW6RE=,tag:nl2bcvdwtkB7fyslVNnpOg==,type:str]
    password: ENC[AES256_GCM,data:qDl72Dw=,iv:uSuutrgRq/kOGhDR7/ziRiKHkHWtudjkPkxNVtec1Ag=,tag:0Ds8k5oDFI/keJM4GqYTTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-assets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:WB0YNAOgtLGj4dwzn7If74PIaBI=,iv:xY/MAWXIHrxEiEIJbPzN58kL1iuWbCcfp/9UVNjBN9M=,tag:IKDfDvva0JK3oPf2aoOUBQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:NNOfRYTsQ/TVaI4fu9kX3arvVKCvGbUXzqLwd8ehQSOASeIZ,iv:wXGR+TJU4tKpPiichkv2IIhS8iI7XZl/sVvPRy/uf/s=,tag:6Vn7E/RRk/2ifjeA2DuZtw==,type:str]
    region: ENC[AES256_GCM,data:zt2noELd,iv:/DhLSYWCQYcI5EGZpIXCe4dmv5hwOZLhBtbpbSoOAj0=,tag:+XKlITTkCNMQOUYWNCbW6w==,type:str]
    bucket: ENC[AES256_GCM,data:Ra1Cw6avwS0ofMfhucXAbkOtkw==,iv:z3HI/Sovr454CoB6uzyFwwpZ9/rnk8veWl24EdqusOY=,tag:u3L2Qhh/0RlOn0ABtKQsRw==,type:str]
    endpoint: ENC[AES256_GCM,data:/6hUHYeNRGRQW/JOjgNnppU5BXicuq9E+wiS,iv:PD8YBWd8t2dyn6XW0E9aIhaybaW3XP5NAW8y0xPlUic=,tag:OBq4M80KoCzF/h2o472rGw==,type:str]
    cdn: ENC[AES256_GCM,data:B44wHaCCVuCmmYCa4sskczcFxqQDuzsLE9Mcr6VG/DQ6/Otn6CaEb9ghjTfTlQg=,iv:3YNMqBxTPf8qlAdVC75JlJrHgLl7bVvRfR/6FRaSpvo=,tag:FwlNUDROI5OYEl6eKnv8Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:PCefxUw/xbhrEMCixVz/YlgjJqk=,iv:SjZ2VV0wuPF7yNZpscavS2hDfaQYR+/7Oll0cvAXNzM=,tag:ctfzEL0eXrnRXkQhogZvQw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:cQtFMLwxDj1FC/PUdMGU2JZKdCTCEPEDtiF/rgOFYNx4Eddl,iv:oK7pXJUigUir+P5/A2UooOQ22h1ZQfRdNfB5FwIjVHA=,tag:TMp2VFCWipOdnRequ+aQsw==,type:str]
    region: ENC[AES256_GCM,data:kdjFMGyH,iv:OBgOCqF6NXXJ7I0EpcYbxQ4N2SiGuR6VHhWs0Kmq9Co=,tag:Pu2YADEdy7otTZ82HZKERg==,type:str]
    bucket: ENC[AES256_GCM,data:lE09dJvh0WXLV75TVSAbWQ0aDHE=,iv:z+FGBGqFPMQlF4RTMsUOcKHudAG3PNikNB24PwtFi4s=,tag:XQUrJNLPSMYKFVmD2RewfQ==,type:str]
    endpoint: ENC[AES256_GCM,data:M22NdnQPks3uRvwvk7y2EPuEY5Sw7hNfqlHL,iv:m5TKQ19D0tBOwdeJFUs6WuKdV/BVkGTPyXx9/TSNWXs=,tag:FMK7+v4PhrTQUzCh1intkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ses
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:i5HXAgaTw9eH0wRaGzlFr6V3/xo=,iv:F4VqPJtZMbyRFHkJm9XWHhL1tPkNC4wehrK0U5pTRQs=,tag:pPSDgfhWc0kMbAsrBGDjDg==,type:str]
    secret: ENC[AES256_GCM,data:x4RU6bxbcm4HKB8oZ2N928XmOmI1P4TqfFBvEpNLA9nPlA9fcM3khA==,iv:1a2+zJdtnzkj6J2lR2NuQS0yT+Hew0RxLQ+ZgJ2eWO4=,tag:hU1pODlq4EEm5YrcQbA+PQ==,type:str]
    region: ENC[AES256_GCM,data:eUiT4d41vD+n,iv:pSbrNaLHuS845II3eMy90OhBV93qTqCtFI/oGIk+eyQ=,tag:ynkNtVMTEZ4UYF09GOMVGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
kind: Secret
metadata:
    name: google-analytics
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    trackingId: ENC[AES256_GCM,data:jt0muj7iBA16EqqN0UY=,iv:TRpgqd1737XScg+7Z8ESsxhL1cYjwpMoeaisZ3FhqrQ=,tag:jNUL11EGr9uDMUZNAa+A+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-22T08:54:30Z'
    mac: ENC[AES256_GCM,data:DYelGZCtvMOZYXWA97EURgi6kEj460fSqWb8Or5P5A4nKW2/PrDwIz5aJXRM3/g2SXgGj9uHd+TJ3lZJpOJqt7BwAXgqcLGc9FEyFQqPppZeh4XUyp2THwKyO8mFMUSpR3AWbtW1KxWZOFAk183gj02zaZi82QsXEiEODcuHgus=,iv:ce+Yk+66MAMglH0jp3cAlSLO/r2hqC4+uWcUCuPt2xM=,tag:RxNCYILEkNB3Fz2GU7PNnw==,type:str]
    pgp:
    -   created_at: '2020-08-22T08:54:30Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAuZeNMXam6X170vWBrpSmjsOipePUNjEywoGDsIkuH8Bo
            7WVsKSWqMwXqW38yj8eipz97Zl/6/crNUhql5w+cnpmbFf2CSqCfRfNPtluj/L9C
            /HHF/2+obfQZGVSKhBUM3DWcgvzcFx/AmyqnXeY6t+jqktSWUaN9L+bYro+RWALd
            H2eNUeVbcNQaRMwWL9lsapAUbBZ9qSOAHgfS4Z0pqXpcdNur7AyYWPcw5BJJV9tK
            Yo+Wfsn6vH6LW3Fr1V9tA+4qoaHntBnqy+4sTlrNkP/n5nCKzuLy6OYyGqRgMVRx
            S2Z0L+O3IZGpjIDVWkSC5OxDEZNI7yOUcwQ4IprRlOhApLDryAs6CSBtATZ6Jo91
            0h8hU1PFXWz3U2QIi64evxpLTsLtdfyZFK0c2D3FGHmGEjTEAggvOYjTskxMCWg1
            e16GyBl7y99rNeDP2kM+KwYOpnvPD1idK494hhr3aDouvV+ucyI/Gfoigj34rlcV
            Jw/+5lH5qqeZVlQt6DAMEnNmZ5I3TshXehXYXPh19UrBhJ8tsrRzaun63nVIb417
            RHCzHZFV9tySTRPfBtRiIMXT1mfYjE55oPlEYpjEG78LdvDdlz2zHYzEh2ASp/A1
            W6cKDUHRuT4ndbx8RrkEXTEwx3/i9VxybIg5Y5voWgLJ+/PNQo63HXyn3xApTxzS
            XAEx8i5nJzJu4+6j/a3NwBxy/nEuEy93l7Mcs8DTl2iCGx16bz98DrDMOED+k06V
            fYwVOAqVZCzfvRhykfQ9RA+bM+306cJD0WUTCVgQCDDcW2fa6aeXDTKJCWlb
            =n+d4
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
