apiVersion: v1
kind: Secret
metadata:
    name: prod-route53-credentials-secret
    namespace: cert-manager
    annotations:
        kustomize.config.k8s.io/needs-hash: "false"
type: Opaque
stringData:
    secret-access-key: ENC[AES256_GCM,data:lJzl0FrCaRDxqHR3ZGwk2x6dlgFY9W3psp59GRN5exVME261Ns0LXQ==,iv:RfVVmKex1IoqEKSNJKcWMPDf7/3RZGKSwRV8bu1S+CY=,tag:aHWHqNhvQym2GlYwjxaLSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-09-03T21:12:00Z'
    mac: ENC[AES256_GCM,data:XLBc4MGpbfAL7ZwhbG8JvwYER2ZqRI+wx6mY0JAJrry739APZgIv+se49AiVR/X4EKtTvHUtujpHhk/tgLGxEOZxd19Ei/zyRGQB9Ku23U1PFVXIPjfDcZi7x+01JJaoCULWccmIMJEu9jI5trNJxEx13j7nIfvIkA3rHECwM64=,iv:nO0nbPeiUIziCZy+pcqtCrn5BsZnjPI8FNBLz7wVtZo=,tag:i79o5RHq7CVNjNrvfH+HSg==,type:str]
    pgp:
    -   created_at: '2021-09-03T21:12:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAi/tiaqk75P44Ch370b8OwOGFBdFKqj0+DffirAhIn4d7
            5qSmaRYIYJGw6Un/JMIIMJrZjArFEli4wvzIR4R0YPFvzQOOnKFd/CZS6sNLLTfc
            tyekE7QUZc9xg8WJEquyOHkTPDPcNUGIVBKspRsWgJ8SKtFSL8dDG8PjKiEUzCHV
            rlgTa91qc9NnW6EeOyG7x8+Hcx3FOwxDB8ttwFo7rbck8ivEeNMwldOcSPGOUJUR
            ARSgwUwhHyaDqcLgW7F2ujhbNW0LFHgNnfwlTA8esoaAmUXWak4elgBstswsx8i/
            CZZEEdK8AZDSD7bmh3mXT9Zwd1I8UCHJe2z+1Aaw/+a+uB5L1ft8wj4dlVgaUI3L
            GQvhlK1Bn6YPHVFfcAim6ldloFJwHB42pRp5/8hv4RZUoH39+q03/fMIw2mxe+wW
            D5EumJC8w9vrcjkD0p7i/6hXKD5pqgRgQN5xFiFwH4ldbLqKqkhDD2orsVSiQAp5
            U5+Z3xRclFXmGfnudPZG1NONCmD2T0Nf4t7GINtqwoSGpkt73igxOQYv5Oj96Rv0
            d6hsl3wRvUTxVeIl4hVW6y7dsOv90Ivsvn7Xf/ekD3E1nHurpb+3ZfYqEgWnuQpa
            VxtmUHnBjTutmjZSIYFAZ7VTQIPVU6Lp49BXZfW7ew6081qkanf7CWykiRDxsYLS
            XgHySxpy6NWV/IrTINqxUEXQGsU6BddnTpwecSpi9EXjrE/MmvKcB0kl3+JDtIcg
            sgRu/w834M59i3XgRZ3JCsMs10pq/n7wLJ492G1XdvCeeIJAqKeGGNQbM9aetmQ=
            =HPfI
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-jkanda-api-token-secret
    namespace: cert-manager
    annotations:
        kustomize.config.k8s.io/needs-hash: "false"
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:bwkMjr2lcFSjVCd9AsohEYoL8TL4FKdkbUuU5L/PCvFmaLVv72iZwQ==,iv:4sfoK9WIaFoszEctV23ryNiPLuvDleisgmWj+bsICNc=,tag:NdkSkVvIYTD9k0BzLpTxvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-09-03T21:12:00Z'
    mac: ENC[AES256_GCM,data:XLBc4MGpbfAL7ZwhbG8JvwYER2ZqRI+wx6mY0JAJrry739APZgIv+se49AiVR/X4EKtTvHUtujpHhk/tgLGxEOZxd19Ei/zyRGQB9Ku23U1PFVXIPjfDcZi7x+01JJaoCULWccmIMJEu9jI5trNJxEx13j7nIfvIkA3rHECwM64=,iv:nO0nbPeiUIziCZy+pcqtCrn5BsZnjPI8FNBLz7wVtZo=,tag:i79o5RHq7CVNjNrvfH+HSg==,type:str]
    pgp:
    -   created_at: '2021-09-03T21:12:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0cJk9LF2A5mARAAi/tiaqk75P44Ch370b8OwOGFBdFKqj0+DffirAhIn4d7
            5qSmaRYIYJGw6Un/JMIIMJrZjArFEli4wvzIR4R0YPFvzQOOnKFd/CZS6sNLLTfc
            tyekE7QUZc9xg8WJEquyOHkTPDPcNUGIVBKspRsWgJ8SKtFSL8dDG8PjKiEUzCHV
            rlgTa91qc9NnW6EeOyG7x8+Hcx3FOwxDB8ttwFo7rbck8ivEeNMwldOcSPGOUJUR
            ARSgwUwhHyaDqcLgW7F2ujhbNW0LFHgNnfwlTA8esoaAmUXWak4elgBstswsx8i/
            CZZEEdK8AZDSD7bmh3mXT9Zwd1I8UCHJe2z+1Aaw/+a+uB5L1ft8wj4dlVgaUI3L
            GQvhlK1Bn6YPHVFfcAim6ldloFJwHB42pRp5/8hv4RZUoH39+q03/fMIw2mxe+wW
            D5EumJC8w9vrcjkD0p7i/6hXKD5pqgRgQN5xFiFwH4ldbLqKqkhDD2orsVSiQAp5
            U5+Z3xRclFXmGfnudPZG1NONCmD2T0Nf4t7GINtqwoSGpkt73igxOQYv5Oj96Rv0
            d6hsl3wRvUTxVeIl4hVW6y7dsOv90Ivsvn7Xf/ekD3E1nHurpb+3ZfYqEgWnuQpa
            VxtmUHnBjTutmjZSIYFAZ7VTQIPVU6Lp49BXZfW7ew6081qkanf7CWykiRDxsYLS
            XgHySxpy6NWV/IrTINqxUEXQGsU6BddnTpwecSpi9EXjrE/MmvKcB0kl3+JDtIcg
            sgRu/w834M59i3XgRZ3JCsMs10pq/n7wLJ492G1XdvCeeIJAqKeGGNQbM9aetmQ=
            =HPfI
            -----END PGP MESSAGE-----
        fp: CAF0E344F537DA3B7D12DA0FA2581E729A833849
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
