apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  storageClassName: scw-bssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
