apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
