apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert-agravelot.eu
  namespace: istio-system
spec:
  secretName: ingress-cert-wildcard-agravelot.eu
  dnsNames:
    - "accounts.agravelot.eu"
    - "admin.agravelot.eu"
    - "frontend.agravelot.eu"
    - "agravelot.eu"
    - "api.agravelot.eu"
  issuerRef:
    #name: selfsigned-issuer
    #name: letsencrypt-staging-dns
    name: letsencrypt-prod-dns-agraveot.eu
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
