---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - virtualservice.yml

configMapGenerator:
  - name: nginx-conf-d-config
    files:
      - default.conf
