version: '3.7'

services:

  db:
    image: postgres:14-alpine
    # restart: always
    environment:
      POSTGRES_DB: flasher
      POSTGRES_USER: flasher
      POSTGRES_PASSWORD: flasher
      TZ: "Europe/Paris"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw,delegated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: