version: "3.7"

services:
  db:
    image: postgres:14-alpine
    # restart: always
    environment:
      POSTGRES_DB: flasher
      POSTGRES_USER: flasher
      POSTGRES_PASSWORD: flasher
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Europe/Paris"
    ports:
      - "5432:5432"
    volumes:
      - db-data2:/var/lib/postgresql/data:rw,delegated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio2_storage:/data
#    environment:
#      MINIO_ROOT_USER: 
#      MINIO_ROOT_PASSWORD: 
    command: server --console-address ":9001" /data
    
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/

volumes:
  db-data2: {}
  minio2_storage: {}
  rabbitmq_volume: {}