apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    keel.sh/approvals: "1"
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/notify: deployments
    # keel.sh/match-tag: "true" # only makes a difference when used with 'force' policy, will only update if tag matches :dev->:dev, :prod->:prod 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: frontend-nginx-conf-d-volume
          configMap:
            name: frontend-nginx-conf-d-config
        - name: nginx-cache-volume
          persistentVolumeClaim:
            claimName: pvc-nginx-cache
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - image: library/nginx:1.18-alpine
          imagePullPolicy: IfNotPresent
          name: frontend-nginx
          command:
            - "nginx"
            - "-g"
            - "daemon off;"
          volumeMounts:
            - name: frontend-nginx-conf-d-volume
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache-volume
              mountPath: /var/lib/nginx/cache
          ports:
            - name: http-frontend
              containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - image: frontend
          imagePullPolicy: Always
          name: nextjs
          ports:
            - name: http-nextjs
              containerPort: 3000
          # envFrom:
          #   - configMapRef:
          #       name: frontend-config
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_ALGOLIA_APP_ID
              valueFrom:
                secretKeyRef:
                  key: ALGOLIA_APP_ID
                  name: api-secret
            - name: NEXT_PUBLIC_ALGOLIA_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ALGOLIA_SECRET
                  name: api-secret
            - name: NEXT_PUBLIC_GOOGLE_ANALYTICS_UA
              valueFrom:
                secretKeyRef:
                  key: trackingId
                  name: google-analytics
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "3000m"
        # - image: h2non/imaginary:latest
        #   imagePullPolicy: IfNotPresent
        #   name: frontend-imaginary
        #   ports:
        #     - name: http-imaginary
        #       containerPort: 9000
        #   env:
        #     - name: PORT
        #       value: "9000"
        #     - name: MALLOC_ARENA_MAX
        #       value : "2"
        #   command:
        #     - imaginary
        #     - -enable-url-source
        #     - -allowed-origins
        #     - https://assets-jkanda.s3.fr-par.scw.cloud,https://assets.blog.jkanda.s3.fr-par.scw.cloud,https://s3.fr-par.scw.cloud
        #     - -concurrency
        #     - "6"
        #   readinessProbe:
        #     httpGet:
        #       port: 9000
        #       path: /