apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-cache
  labels:
    app: frontend
spec:
  storageClassName: scw-bssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
