apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-virtualservice
spec:
  hosts:
    - "api.agravelot.eu" # TODO Only replace this line
  gateways:
    - flasher-gateway
  http:
    - route:
      - destination:
          host: api
          port:
            number: 80
      headers:
        # request:
        #   add:
        #     Accept: application/json
        #     Content-Type: application/json
        response:
          add:
            Strict-Transport-Security: max-age=31536000; includeSubDomains
            X-Robots-Tag: "noindex, nofollow"
      corsPolicy:
        allowOrigins:
           - exact: https://agravelot.eu
           - exact: https://admin.agravelot.eu # TODO Only replace this line
           - exact: http://localhost:3000 # TODO Only replace this line
           - exact: http://localhost:3000
        allowHeaders:
          - authorization
          - content-type
          - cache-control
          - x-requested-with
        allowMethods:
          - OPTIONS
          - GET
          - POST
          - PATCH
          - DELETE
        allowCredentials: true
        #maxAge: "24h"



