// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Album is the predicate function for album builders.
type Album func(*sql.Selector)

// AlbumCategory is the predicate function for albumcategory builders.
type AlbumCategory func(*sql.Selector)

// AlbumCosplayer is the predicate function for albumcosplayer builders.
type AlbumCosplayer func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Cosplayer is the predicate function for cosplayer builders.
type Cosplayer func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)
