---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  #strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: realm-import-volume
          configMap:
            name: realm-import-config
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - image: keycloak
          name: keycloak
          env:
            - name: KEYCLOAK_IMPORT
              value: "/tmp/import/realm.json"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: database.vendor
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: database.host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: KEYCLOAK_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: database.name
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: password
          volumeMounts:
            - name: realm-import-volume
              mountPath: /tmp/import
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
