apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  meshConfig:
    outboundTrafficPolicy:
#      mode: REGISTRY_ONLY
      mode: ALLOW_ANY
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 400m # override from default 500m
            memory: 512Mi # ... default 2048Mi
