namespace: flasher-dev

resources:
  - ../../base
  - persistent-volume.yml

patchesStrategicMerge:
  - api/authorization-policy.yml
  - api/virtualservice.yml
  - admin/virtualservice.yml
  - tusd/authorization-policy.yml
  - tusd/virtualservice.yml
  - keycloak/virtualservice.yml


configMapGenerator:
  - name: api-config
    literals:
      - APP_ENV=staging
      - BROADCAST_DRIVER=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - SCOUT_DRIVER=null
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_DEBUG="true"
      - APP_KEY=base64:ZaGAQgCskW36RnpnZJ5l313oRExNqQ6XumgjjFWHIvY=
      - DB_CONNECTION=pgsql
      - DB_DATABASE=flasher
      - DB_HOST=postgres
      - DB_PORT="5432"
      - DB_USERNAME="admin"
      - DB_PASSWORD="admin"
      - LOG_CHANNEL=stderr
      - KEYCLOAK_URL=https://accounts.172.17.0.1.nip.io:31396
      - KEYCLOAK_BASE_URL=https://accounts.172.17.0.1.nip.io:31396/auth
      - KEYCLOAK_REALM=jkanda
      - KEYCLOAK_CLIENT_ID=flasher
      - KEYCLOAK_VERIFY_SSL=false
      - KEYCLOAK_MASTER_USERNAME=admin
      - KEYCLOAK_MASTER_PASSWORD=admin

  - name: nginx-config
    literals:
      - log.level="debug"

  - name: keycloak-config
    literals:
      - database.vendor=POSTGRES
      - database.name=keycloak
      - database.host=postgres

  - name: admin-config
    literals:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=80
      - BASE_URL=https://172.17.0.1.nip.io:31396/admin
      - REMOTE_API=https://172.17.0.1.nip.io:31396
        - KEYCLOAK_REMOTE_HOST=https://accounts.172.17.0.1.nip.io:31396
      - KEYCLOAK_REALM=jkanda
      - KEYCLOAK_CLIENT_ID=flasher
      #- DEBUG=nuxt:*

secretGenerator:
  - name: postgres-secret
    literals:
      - user=admin
      - password=admin
  - name: keycloak-secrets
    literals:
      - user=admin
      - password=admin

images:
  - name: nginx
    newName: registry.gitlab.com/flasher/flasher/picblog_nginx
    newTag: 9af451
  - name: php
    newName: registry.gitlab.com/flasher/flasher/picblog_php
    newTag: c0f794
  - name: tusd
    newName: docker.io/tusproject/tusd
    newTag: v1.2.0
  - name: keycloak
    newName: registry.gitlab.com/flasher/flasher/keycloak
    newTag: latest
  - name: admin
    newName: registry.gitlab.com/flasher/flasher/flasher-admin
    newTag: local
  - name: postgres
    newTag: 12-alpine
