apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
  claimRef:
    name: pvc-postgres
    namespace: flasher-dev # TODO Inject namespace
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/redis"
  claimRef:
    name: pvc-redis
    namespace: flasher-dev # TODO Inject namespace
