name: api-go

on:
  push:
    paths:
      - "apps/api-go/**"
      - ".github/workflows/api-go.yml"
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    paths:
      - "apps/api-go/**"
      - ".github/workflows/api-go.yml"

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-22.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Gitlab
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.gitlab.com/flasher/flasher/flasher-api-go # list of Docker images to use as base name for tags
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push base
        uses: docker/build-push-action@v3
        with:
          context: ./apps/api-go
          file: ./apps/api-go/Dockerfile
          push: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUF_TOKEN=${{ secrets.BUF_TOKEN }}
  test:
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: flasher
          POSTGRES_PASSWORD: flasher
          POSTGRES_DB: flasher
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 150
        ports:
          - 5432:5432
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-22.04 ]
    # runs-on: self-hosted
    runs-on: ubuntu-22.04
    steps:
      - name: Install golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - uses: bufbuild/buf-setup-action@v1.13.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: 1.10.0
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: apps/api-go
      - uses: bufbuild/buf-breaking-action@v1
        with:
           input: apps/api-go
           against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=apps/api-go"
      - name: Set up gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Init DB
        run: |
          cd apps/api-go/migration
          go run github.com/pressly/goose/v3/cmd/goose@latest postgres "postgres://flasher:flasher@localhost:5432/flasher?sslmode=disable" up
      - name: Test
        run: |
          cd apps/api-go
          set -euo pipefail
          go test -race -coverprofile=coverage.out -covermode=atomic -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
        env:
          DB_HOST: localhost
          DB_USER: flasher
          DB_PASSWORD: flasher
          DB_NAME: flasher
          DB_PORT: 5432
          APP_HTTP_PORT: 3000
          APP_GRPC_PORT: 3100
          DB_SSL_MODE: disable
          DB_URL: postgresql://flasher:flasher@localhost:5432/flasher?sslmode=disable
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_APIKEY }} # not required for public repos
          directory: apps/api-go
          # files: ./coverage1.xml,./coverage2.xml # optional
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          # fail_ci_if_error: true # optional (default = false)
          # verbose: true # optional (default = false)
